### ISSUE TITLE
Fingerprint_post_processing_step1_lincs.R terminates after going through 184,463 samples

### ISSUE THREAD

**Issue by BioSok** [hidelab/lincs-pathprint#1]
The script terminates on HPC before it goes through all samples. The termination happens in here:
```# construct list of fingerprints - SCGs (single chip gene set enrichments) - and platforms
# This displays a running total of the arrays processed for tracking
SCE<-vector("list", length(files))
platform<-vector("list", length(files))

for (i in 1:length(files)){
  load(files[i])
  print(i)
  SCE[[i]]<-temp1[[1]]$SCG
  platform[[i]]<-temp1[[1]]$platform
}```

**Comment by BioSok** [comment]
It doesnt seem to stop to a specific experiment or after a specific number of experiments. It stops around 180K samples. Shoud investigate memory issues!

**Comment by wenbinwei** [comment]
What is the error message from HPC?

**Comment by BioSok** [comment]
When the script is run interactively on HPC it just terminates without a message, it just says: Terminated. When I run it as a batch, before it starts (and while it's in queue) I get this Eqw state when looking for jobs on hidelab node: 

3203556 0.32338 processing md1skar      **Eqw**   12/07/2017 14:14:13                                   12

**Comment by BioSok** [comment]
The issue was resolved by fixing a specific path  in the script that was causing the Eqw error.
